CREATE TABLE USERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(70) NOT NULL ,
EMAIL_ID VARCHAR(80) UNIQUE NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
ACTIVE BOOLEAN DEFAULT 1
); 
SELECT *FROM USERS;


CREATE TABLE DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  ACTIVE BOOLEAN DEFAULT 1,
  PRIMARY KEY (ID)
);
INSERT INTO DEPARTMENT(NAME) VALUES ('HR'),('FINANCE')
SELECT *FROM department;
 
  
CREATE TABLE ROLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(100) NOT NULL,
 ACTIVE BOOLEAN DEFAULT 1
 );

INSERT INTO role(NAME) VALUES('HR'),('MANAGER'),('TRAINER'),('EMPLOYEE')
  
 SELECT *FROM ROLE ;


CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY AUTO_INCREMENT,
DEPT_ID INT NOT NULL,
ROLE_ID INT NOT NULL,
NAME VARCHAR(60) NOT NULL,
EMAIL_ID VARCHAR(60) UNIQUE NOT NULL,
PASSWORD VARCHAR(90) NOT NULL,
ACTIVE BOOLEAN DEFAULT 1 ,
CONSTRAINT FK_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID),
CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);
SELECT *FROM employee;


CREATE TABLE TRANSACTION(  
  ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT ,
  EMP_ID INT ,
  DEPT_ID INT ,
  ASSINGTO VARCHAR(100),
  SUBJECT VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUS VARCHAR(100) DEFAULT 'open' ,
  PRIORITY VARCHAR(100),
  PRIMARY KEY (ID),
  CONSTRAINT FK_UID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT FK_EID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(ID),
  CONSTRAINT FK_DID FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)
);
SELECT *FROM TRANSACTION


CREATE TABLE ISSUES (
  ID INT NOT NULL AUTO_INCREMENT,
  TICKET_ID INT NOT NULL,
  EMP_ID INT NOT NULL,
  SOLUTION VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
   CONSTRAINT FK_ID FOREIGN KEY (TICKET_ID) REFERENCES TRANSACTION (ID),
   CONSTRAINT FK_EM FOREIGN KEY(EMP_ID) REFERENCES  EMPLOYEE (ID)
   );
  

 



